### ISSUE TITLE
extension causes long pause when using self-signed ssl certificate

### ISSUE THREAD

**Issue by ck-on** [gavinhungry/cipherfox#14]
After some trial and error I hunted down a long delay caused by cipherfox.

I use several personal sites with a self-signed SSL certificate and out of laziness I just use a generic domains (ie. "example.com" or "localhost") as the certificate domain.

I didn't experience this bug with FF28 but with FF30 and FF31 there is a long delay before loading the page and more importantly, there is a long delay just switching back and forth to the tab with the page that has the https and self-signed cert.

No problem with sites using real certificates.

Disabling cipherfox completely eliminates the delay with page load/tab switching.

It is trying to access the fake domain? Is it not caching the result between tabs?

Maybe a temporarily workaround could be not to try to access "localhost" or "127.0.0.1"

**Comment by gavinhungry** [comment]
Closing unless this can be reproduced. @ck-on, feel free to open this if you have anything to add.
