### ISSUE TITLE
Missmatch ssllabs and cipherfox

### ISSUE THREAD

**Issue by habakuk007** [gavinhungry/cipherfox#26]
Hi,
I use Firefox 36.0 / Win 7.0 and if I disable rc4 the connection to https://www.wufoo.com/ is blocked (ssl_error_no_cypher_overlap ), but if I check it with https://www.ssllabs.com/ssltest/analyze.html?d=atlassian.wufoo.com it says that it should be secure:  	TLS 1.2, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014), FS, 256 

Why?

Best regards!
    Stefan

**Comment by gavinhungry** [comment]
@habakuk007,

I can connect to that site just fine, with RC4 enabled (Firefox 36.0, Linux). Maybe you disabled some other cipher suites by accident?

I connect with `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` (`security.ssl3.ecdhe_rsa_aes_256_sha`). Is that enabled for you in about:config?

**Comment by habakuk007** [comment]
Thanks for your answer.

I think that the option `security.tls.version.max` was set wrong - it was set to 1 now I reseted it to default.

I have no idea why it was set...

Ciao!
   Stefan

**Comment by gavinhungry** [comment]
Glad its working!
