### ISSUE TITLE
No information in Site ID dialog for partially encrypted sites

### ISSUE THREAD

**Issue by Poohblah** [gavinhungry/cipherfox#27]
I don't see encryption information for pages where not all elements are encrypted, e.g.:
![2015-04-16-161725_3840x1200_scrot](https://cloud.githubusercontent.com/assets/3742215/7192618/74a2c69e-e454-11e4-868e-e75c6f7b26cc.png)
Here is a screenshot to confirm that cipherfox works otherwise:
![2015-04-16-161911_3840x1200_scrot](https://cloud.githubusercontent.com/assets/3742215/7192619/74a34128-e454-11e4-8655-e794d74add6d.png)
This is for ciperfox 3.10.1 on Firefox 37.0.1 on Linux.

**Comment by Der-Orden** [comment]
No problem here. have u enabled the option to show TLS-Information on non full encrypted sites?
You can find it in the CipherFox options:
![cf1](https://cloud.githubusercontent.com/assets/10184283/7215329/014da184-e5d3-11e4-833a-6d95f141687c.PNG)

**Comment by gavinhungry** [comment]
@Der-Orden is correct. By default, CipherFox does not appear at all for partially-encrypted pages. Doing so by default could give users the impression that their entire session is secure. You have to opt-in for that feature.

**Comment by Poohblah** [comment]
The checkbox is ticked in my CipherFox preferences, but I still don't see the encryption cipher information in the Site ID dialog. :( I see the same behavior with Firefox 37.0.1 on OS X as well.

> By default, CipherFox does not appear at all for partially-encrypted pages. Doing so by default could give users the impression that their entire session is secure.

I disagree. Firefox already displays the warning icon instead of the lock icon to convey this piece of information.

**Comment by gavinhungry** [comment]
> The checkbox is ticked in my CipherFox preferences, but I still don't see the encryption cipher information in the Site ID dialog. :( I see the same behavior with Firefox 37.0.1 on OS X as well.

Post a screenshot of your current CipherFox preferences, if you can. I'm using CipherFox 3.10.1 on Firefox 37.0.1 on Linux and it works as expected. I'm using this page to test: https://gavinhungry.io/partial.html

What domains/pages are you trying this on?

> I disagree. Firefox already displays the warning icon instead of the lock icon to convey this piece of information.

In any case, if it's not working for you now with the option checked, it's not going to work if I change the default (which I'm not going to do anyway :).

**Comment by Poohblah** [comment]
I'm using https://www.colorado.edu/user to test - this site is not working for me. Looks like https://gavinhungry.io/partial.html works for me.

Here is the requested screenshot (on OS X this time):
![untitled](https://cloud.githubusercontent.com/assets/3742215/7236914/3c451302-e755-11e4-80df-34f350d0040d.png)

> In any case, if it's not working for you now with the option checked, it's not going to work if I change the default (which I'm not going to do anyway :).

True. And while I disagree with this design decision (I'm in the "provide sensible defaults, and fewer options are better options" camp), this issue isn't about the design decisions of CipherFox, just functionality... so I guess I'll shut up about the topic of design for now :)

**Comment by gavinhungry** [comment]
> True. And while I disagree with this design decision (I'm in the "provide sensible defaults, and fewer options are better options" camp), this issue isn't about the design decisions of CipherFox, just functionality... so I guess I'll shut up about the topic of design for now :)

Well, Firefox itself won't show you the cipher being used if the session is partially encrypted:
**Connection Partially Encrypted** vs.
**Connection Encrypted (TLS_ECHDE_*...*, 128 bit keys, TLS 1.2)**

Anyways, https://www.colorado.edu/user doesn't display CipherFox for me either. Hmm. Thanks for the link, I'll look into this.

**Comment by gavinhungry** [comment]
The issue (from CipherFox's perspective) is that **`SSLStatus`** (`securityUI.QueryInterface(...).SSLStatus`) is **`null`**.

I was suspecting that the domain does not have SSL/TLS configured correctly. Even just visiting this standalone image (ostensibly via SSL/TLS) that is included on the page you linked gives a "partially encrypted" message:
https://www.colorado.edu/profiles/cu_homepage/themes/cu_960_responsive/images/print-logo.png

Results from [Qualys SSL Labs Server Test](https://www.ssllabs.com/ssltest/):
https://www.ssllabs.com/ssltest/analyze.html?d=www.colorado.edu

A number of issues, not the least of which is supporting **only** RC4.

*But*, both that image and the page itself load fine in Chrome, with no mixed-content warning. Hmm indeed.

**Comment by gavinhungry** [comment]
I think that supporting RC4 (and only RC4) is the culprit here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1093595
https://developer.mozilla.org/en-US/Firefox/Releases/36#Security

> RC4 is now considered as insecure and all UI indicators will react as such

**Comment by Poohblah** [comment]
Yes, we were debugging cipher suite issues on on the ssl termination device for www.colorado.edu (incl. dev and test as well) when I came across this issue with CipherFox.  Chrome has no problem with RC4, which may be why the devs haven't noticed any problems with SSL on the site recently.

**Comment by Poohblah** [comment]
In any case, I was trying to use Firefox to confirm what ciphers the sites in question were using. Even if Firefox considers a particular cipher to be insecure, is it possible to use CipherFox to get information about that cipher on the current connection?

**Comment by gavinhungry** [comment]
@Poohblah, I honestly don't know. `nsISSLStatus` is the only interface I know of to this data, and if Firefox isn't providing it in these cases, I'm not sure what else I can do.

**Comment by Poohblah** [comment]
Ok.  So it sounds like Firefox doesn't have the proper tools to debug the "insecure cipher" warning in all cases. Thanks for looking into this.

On a side note, you may have noticed that we are no longer using RC4.

**Comment by gavinhungry** [comment]
Closing, since this isn't a CipherFox issue.
