### ISSUE TITLE
Proper Firefox 4+ widget

### ISSUE THREAD

**Issue by rmenessec** [gavinhungry/cipherfox#28]
CipherFox still uses an entry in the old status bar, which you have to install one or more extensions to get back in modern releases of Firefox. (Or, if there is a Firefox 4+ widget, it's well-hidden.)

This is one of the very last extensions I have installed that doesn't have its own widget or widgets for Firefox 4+. The "Show CipherFox in Add-ons Bar" option is promising, but actually toggles whether it appears in the legacy status bar (if it exists at all).

**Comment by gavinhungry** [comment]
CipherFox can appear in the Add-ons bar (which is useful for SeaMonkey and Pale Moon) and/or in the Site ID dialog (useful in Firefox). It doesn't quite match the style of the modern (41+) Firefox builds, but that's another issue.
