### ISSUE TITLE
Add support for Pale Moon

### ISSUE THREAD

**Issue by gavinhungry** [gavinhungry/cipherfox#29]
See:
http://forum.palemoon.org/viewtopic.php?f=1&t=8160
http://forum.palemoon.org/viewtopic.php?f=13&t=7843&start=20

**Comment by pknhvt** [comment]
I currently use cipherfox in Pale Moon and would like to see the additional information displayed in cipherfox.  I like squarefractal's idea of parsing "the "ugly" string" (see: http://forum.palemoon.org/viewtopic.php?f=13&t=7843&start=20).

**Comment by gavinhungry** [comment]
Also relevant: a4a7a86c24fde3ac7cd7cc876c72a61f919a4ebe

**Comment by sergeevabc** [comment]
Support seems to be broken.
