### ISSUE TITLE
Site ID dialog width is not enough

### ISSUE THREAD

**Issue by Cai0407** [gavinhungry/cipherfox#31]
Firefox 41.0b5 without Cipherfox 3.12.0:
![2](https://cloud.githubusercontent.com/assets/2016274/9601172/dd944eb4-50da-11e5-9f98-2725dcfc0d85.png)

Firefox 41.0b5 with Cipherfox 3.12.0:
![1](https://cloud.githubusercontent.com/assets/2016274/9601181/e9ea7486-50da-11e5-8cbb-1532717112cb.png)

Buttons to show connection information and "details" are not shown...

**Comment by gavinhungry** [comment]
What are our options?

- Truncate the label
- Make the Site ID dialog bigger
- Move CipherFox altogether
- Other?

**Comment by gavinhungry** [comment]
Sorry, did not mean to close.

**Comment by Cai0407** [comment]
Required width is depend on the setting of "Cipher" of Cipherfox ($CIPHERCUITE will be very long in case of ECDHE/GCM).
I think it is better to 
1. make Site ID dialog bigger
and
2. move Cipherfox button above the "details" button by Firefox itself

**Comment by dings-bums** [comment]
You should take a look at Firefox Nightly, Site ID Dialog is work in progress. At the moment it looks as follows:
- CipherFox disappeared
- Dialog has a fixed width
- Buttons and dropdown-lists have a max. width to prevent problems like shown above

Firefox 43.0a1, Build-ID 20150907030206:
![nightly_sid_pt1](https://cloud.githubusercontent.com/assets/14170115/9723958/c5a98af0-55ce-11e5-8262-905bcbf6469b.png)
![nightly_sid_pt2](https://cloud.githubusercontent.com/assets/14170115/9723963/e322b494-55ce-11e5-85c2-2c6ec8ab408a.png)
![nightly_sid_pt3](https://cloud.githubusercontent.com/assets/14170115/9723970/0a43d18e-55cf-11e5-9d35-05a2fd1f9f8d.png)

I think, the best solution for the moment would be a toolbar-button (perhaps like AdblockPlus: hover to show info, click for options).

**Comment by gavinhungry** [comment]
I'm on Firefox 42 (Developer Edition).

@Cai0407, I agree that it should be on its own line to avoid this.  But it does look the dialog is changing (differences between 41, 42 and 43), so I may wait until it settles.

@dings-bums, I greatly dislike "toolbar buttons," so we'll save that as a last result.

I'd like to let CipherFox resize the width of the box, if needed.

**Comment by DaAwesomeP** [comment]
+1 I like both ideas. I prefer the idea to put the first line of the select box on a different line and replace it with something like "More Information." This will probably make it much more future-proof.

If you decide to have the dialog box resize, please be sure to implement a CSS animation on the width if there isn't already one there from Mozilla to make the transition smooth.

This is now seen in the stable and officially released Firefox 43.

**Comment by DaAwesomeP** [comment]
Another option would be to add the select box to the Page Info window as well.

**Comment by dings-bums** [comment]
Would it be possible to repeat the button text as first line or to add an configurable line on the dropdown list? This should fit for $PROTOCOL and $CIPHERSUITE options.

**Comment by DaAwesomeP** [comment]
@gavinhungry Mozilla seems to have settled the styling of the SSL info box for now.

@dings-bums I like that idea. That would solve the problem not matter what the size of the drop down box.

**Comment by dings-bums** [comment]
The next change arrived in Nightly 48.0a1...
![nightly_48 0a1](https://cloud.githubusercontent.com/assets/14170115/14653475/63a65b2e-0679-11e6-8593-6e3cee89d39a.gif)

**Comment by DaAwesomeP** [comment]
@gavinhungry Would you consider @dings-bums' solution? I think that a disabled select box item would work great no matter the layout:
> Would it be possible to repeat the button text as first line or to add an configurable line on the dropdown list? This should fit for $PROTOCOL and $CIPHERSUITE options.

**Comment by gavinhungry** [comment]
@DaAwesomeP I think I like that idea too. I'll implement and see how it looks.

**Comment by DaAwesomeP** [comment]
@gavinhungry Great!

**Comment by DaAwesomeP** [comment]
There is another issue now... The lines of the dropdown have ellipses. This screenshot is from Nightly.
![screenshot 42](https://cloud.githubusercontent.com/assets/4472083/15379243/ddad33e8-1d30-11e6-8b05-6e3ff8d8c53c.png)

**Comment by dings-bums** [comment]
... but it is wide enough to show full ciphersuite and protocol version. Dates should have short format (M/T/JJJJ), but I don't know, whether Chipherfox can change this (probably determined by Firefox).

**Comment by gavinhungry** [comment]
I'll address the "long date" issue under #38.

- Added a "Menu Heading" formatting string, which renders to a disabled menu item at the top of the dropdown. You can use the same formatting string that you use for the button, but this way you're not forced to. The default is `$CIPHERSUITE`. An empty string here removes the header.
- Updated the style to match the latest versions of Firefox.
- Removed the `max-width` on menu items.

Remaining issues:
- Only tested on Firefox 48 on Linux.
- The string "Menu Heading" needs to be localized - I added the English string to each locale.

![phobos-20160601_081035_pdt](https://cloud.githubusercontent.com/assets/744538/15714751/a36b8fcc-27d0-11e6-9874-90e1abb79210.png)
![phobos-20160601_081054_pdt](https://cloud.githubusercontent.com/assets/744538/15714752/a378a446-27d0-11e6-8917-c7f8b458e8d3.png)
![phobos-20160601_081118_pdt](https://cloud.githubusercontent.com/assets/744538/15714753/a385e188-27d0-11e6-9e54-49b2d3b81226.png)

If you're using the add-on bar:
![phobos-20160601_081707_pdt](https://cloud.githubusercontent.com/assets/744538/15714908/560bd24a-27d1-11e6-9ef0-3e3762428cc7.png)

**Comment by gavinhungry** [comment]
Firefox 46, Linux:
![fx46-linux](https://cloud.githubusercontent.com/assets/744538/15720635/0cacd874-27ea-11e6-9bf4-e460b2c9004c.png)

Firefox 46, Windows:
![fx46-win](https://cloud.githubusercontent.com/assets/744538/15720636/0cb0eb30-27ea-11e6-9856-11ddb4325947.png)

Firefox 47-48, Windows:
![fx47-win](https://cloud.githubusercontent.com/assets/744538/15720634/0cacd3b0-27ea-11e6-8954-773c8d96255c.png)
