### ISSUE TITLE
Cipherfox dropdown in site ID dialog is gone in Firefox 42

### ISSUE THREAD

**Issue by ReggX** [gavinhungry/cipherfox#32]
Upgraded to Firefox 42 64bit today and the dropdown disappeared from the site ID bubble.

See also https://github.com/gavinhungry/cipherfox/issues/31#issuecomment-138396109

(Opened as new issue in order to keep disucussion in the other issue on topic)

**Comment by gavinhungry** [comment]
Try CipherFox 3.13.0 (on AMO as of today) - I haven't resolved the width issue (#31), but it supports Fx 42 now.

![CipherFox 3.13.0](https://cloud.githubusercontent.com/assets/744538/10924432/6d02f30c-823b-11e5-9922-3e6a987e1ced.png)
