### ISSUE TITLE
Make statusbar item moveable

### ISSUE THREAD

**Issue by beerisgood** [gavinhungry/cipherfox#33]
Can you please make the statusbar icon moveable?
Here is a screenshot which show the customize option and the Cipherfox item isn't moveable (in Pale Moon 25.8.0 x64)

![cipherfox_statusbar](https://cloud.githubusercontent.com/assets/9625159/11295982/790e02e0-8f6f-11e5-9dd7-59a538c1c55a.png)

**Comment by mattatobin** [comment]
Just for clarification...

What this user wants is to have a choice between the classical statusbar item OR a regular toolbar widget that can be placed anywhere such as a toolbar button-y widget thing that can be arbitrarily moved and placed anywhere in the UI.

**Comment by TPS** [comment]
@beerisgood Has this been accomplished?
