### ISSUE TITLE
New Firefox 43 box does not expand to full size

### ISSUE THREAD

**Issue by DaAwesomeP** [gavinhungry/cipherfox#34]
The new box needs to expand to the proper width, as it just adds an ellipsis to the select box.
![screenshot](https://cloud.githubusercontent.com/assets/4472083/11829719/4c7152ba-a364-11e5-8a7b-a5be0ad4b3e6.png)
Great extension, by the way!

**Comment by gavinhungry** [comment]
Hi @DaAwesomeP,

I think is a duplicate of #31, so I'm closing this - let me know if you feel otherwise. The text was truncated as part of #32, but I do intend to find a decent solution to just widen the Site ID dialog.

**Comment by DaAwesomeP** [comment]
Sorry, I didn't see the other issues. No problem!
