### ISSUE TITLE
Remove RC4-Option

### ISSUE THREAD

**Issue by dings-bums** [gavinhungry/cipherfox#39]
Firefox ESR 38.8 is the last release which supports RC4-fallback by default and will update to ESR 45.2 next week, where this option has no effect any more.

Perhaps you could replace this with an option to block mixed-content pictures (toggle pref 'security.mixed_content.block_display_content'.

**Comment by gavinhungry** [comment]
I think I will also then have to bump the `minVersion` to 45.

https://www.mozilla.org/en-US/firefox/organizations/all/ says that ESR is 45.1.1 though.

**Comment by dings-bums** [comment]
RC4 was disabled with release of Firefox 44 (see https://groups.google.com/forum/#!msg/mozilla.dev.platform/JIEFcrGhqSM/CIjtpwxoLQAJ). ESR does not automatically upgrade to the next major version until the last minor version is eol (normally xx.8).

**Comment by gavinhungry** [comment]
CipherFox is also supported in Pale Moon and SeaMonkey. That doesn't change the fact that RC4 is insecure, so I don't think it's a needed option anymore.
