### ISSUE TITLE
Add support for TLS 1.3

### ISSUE THREAD

**Issue by gavinhungry** [gavinhungry/cipherfox#44]
Via email:

> Are you going to update CipherFox for tls 1.3?

**Comment by gavinhungry** [comment]
`TLS_VERSION_1_3` is exposed on `Components.interfaces.nsISSLStatus`, so this should be a one-line addition. I'm unaware what, if any, sites currently provide TLS 1.3, so I can't readily test this.

**Comment by Der-Orden** [comment]
You can try https://www.cloudflare.com/ 
Currently Firefox 51.0a2 will use TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256  via TLS 1.3 but report it as broken Encryption.

**Comment by gavinhungry** [comment]
@Der-Orden,

Hmm, I'm seeing `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` with TLS 1.2 on Fx 49. I'll try Fx 51.

**Comment by Der-Orden** [comment]
Oh yes, TLS 1.3 is disabled by default.
You need to change security.tls.version.max from 3 to 4

**Comment by gavinhungry** [comment]
@Der-Orden,

Thanks, I just discovered that.

**Comment by gavinhungry** [comment]
![phobos-20161005_102240_pdt](https://cloud.githubusercontent.com/assets/744538/19123963/ed375bae-8ae5-11e6-8113-21d28d0dffbb.png)

This is Fx 51.

**Comment by gavinhungry** [comment]
Fixed in 4.1.0, which has been submitted to AMO. If you can't wait, get it here:
https://addons.mozilla.org/en-US/firefox/addon/cipherfox/versions/?page=1#version-4.1.0
