### ISSUE TITLE
"Qualys SSL Labs Server Test" does not work on Fx 51+

### ISSUE THREAD

**Issue by Cai0407** [gavinhungry/cipherfox#45]
Here is an error log in browser console.

	TypeError: gBrowser.contentDocument is null    cipherfox.js:475:1

	 CipherFox.testDomain                          chrome://cipherfox/content/cipherfox.js:475:1

	 oncommand                                     chrome://browser/content/browser.xul:1:1

**Comment by gavinhungry** [comment]
Seems that we can use `gBrowser.currentURI.host` in place of `gBrowser.contentDocument.domain`. I don't know how far back support for the latter property goes, so we might as well keep the former as well.

**Comment by gavinhungry** [comment]
Looks like we can use `gBrowser.currentURI.host` instead of `gBrowser.contentDocument.domain`, but I'm unsure of how far back support goes for the former. So, we'll check them both.

**Comment by kapitainsky** [comment]
I assume as it is opened it has not been fixed yet? I have started using FF 51 beta and it  "Qualys SSL Labs Server Test" does not work. FF 51 should move to release channel very soon so would be nice to iron it.

**Comment by gavinhungry** [comment]
@kapitainsky,

I forgot about this, thank you. I fixed the issue but did not submit an updated version to AMO. Will fix today.

**Comment by gavinhungry** [comment]
Version 4.1.1 has been submitted to AMO, expect to see it soon.

**Comment by kapitainsky** [comment]
installed and tested. works as expected now. Thx!

**Comment by Cai0407** [comment]
4.1.1 works fine with Fx 51.0beta, 52.0a2, and 53.0a1. Good!
