### ISSUE TITLE
Enhancement request: Switch from SSL labs test to new Observatory by Mozilla

### ISSUE THREAD

**Issue by GdrjirfRtrUhYUdrjUMm** [gavinhungry/cipherfox#46]
Observatory by Mozilla, https://observatory.mozilla.org, performs tests that SSL labs does not but also simultaneously tests with SSL labs, htbridge.com, tls.imirhil.fr, securityheaders.io, and hstspreload.org. It also gives preliminary results faster while the other tests have not yet finished.

**Comment by Cai0407** [comment]
Yes, it seems to be a better choice.

**Comment by gavinhungry** [comment]
I like this as well, and it is an easy change to implement. Now I need to get [my domain](https://observatory.mozilla.org/analyze.html?host=gavinhungry.io) up from its D+ rating.

**Comment by wolfbeast** [comment]
I greatly prefer Qualys and don't necessarily want to broadcast to all of the observatory-linked sites what I'm testing.

In addition, the Mozilla observatory:
- Makes assumptions about what is considered "good practice" that are debatable
- Isn't providing a full report itself
- Is calling anything that isn't exactly "as per Mozilla's decisions" to be **non-compliant** (such BS, sorry but it is!)

So, if you want to change this, please, please make it configurable, and keep a sane default like Qualys or HT Bridge.

**Comment by gavinhungry** [comment]
I think we'll leave Qualys for now.  We can reopen this later as needed.
