### ISSUE TITLE
 Questionmarks for chiper size, type, hash, and other values 

### ISSUE THREAD

**Issue by hzsolt94** [gavinhungry/cipherfox#48]
Hi Gavin,

I'm experiencing the same issue again like #36, this time with the latest 4.1.1 version, Ubuntu 17.04 54.0 (64-bit) Hungarian.

Do you think we can manage to fix this one more time? I'll look around to see if it's still language specific.

**Comment by hzsolt94** [comment]
Yes, it is language specific, setting Firefox to English fixes everything, just like last time.
Was the fix revoked from 4.1.1? Or maybe the "Original Language" detection code in the fix broke?

**Comment by gavinhungry** [comment]
@hzsolt94,

Is this still an issue? I'm unable to reproduce it, as Firefox 56 will not let me install unsigned extensions (` xpinstall.signatures.required` be damned), and Firefox Developer Edition is already 57, which requires WebExtensions. I also can't find the hu-HU language pack for Firefox 52 ESR.

Either way, reopen if this is still something that needs to be fixed.

**Comment by herczegzsolt** [comment]
@gavinhungry Yes, it's still an issue in Firefox 54-56, but to be fair i don't think it can or should be fixed sadly.

Everything is fine in Firefox 52 ESR. I think it's safe to say we must use 52 ESR to have this addon, until it can be reimplemented via WebExtensions.
