### ISSUE TITLE
Add support for TLS 1.3 protocol

### ISSUE THREAD

**Issue by wolfbeast** [gavinhungry/cipherfox#49]
I'm using Cipherfox on Pale Moon. With v27.4.0, TLS 1.3 was added to the browser, which shows up as a "?" in the extension. Could you please add TLS 1.3 support?

**Comment by Cai0407** [comment]
Support for TLS 1.3 has been added by #44. Is something different between Fx and PM?

**Comment by wolfbeast** [comment]
Hmm.. I see it was added in 4.1.0, however I haven't been offered an update past 3.12.0; possibly a version range issue on AMO; I'll look into what's up -- would you be adverse to listing the extension on our own add-ons site?

**Comment by wolfbeast** [comment]
It doesn't look like 4.1.1 works in Pale Moon; there is no display in either the add-ons bar or the identity panel doorhanger.

**Comment by wolfbeast** [comment]
A quick workaround to make 4.1.1 work in Pale Moon shows tls 1.3 is supported for display. Closing this issue.
