### ISSUE TITLE
Certificate chain

### ISSUE THREAD

**Issue by alevesely** [gavinhungry/cipherfox#8]
The certificate chain seems to miss the root certificate.  For example, while editing this report I see "RC4 128-bit" on the cipher field, and when I click it, I would expect:

   GTE Corporation (RSA 1024-bit: MD5)
   DigiCert Inc (RSA 2048-bit: SHA1)
   DigiCert Inc (RSA 2048-bit: SHA1)
   GitHub, Inc. (RSA 2048-bit: SHA1)

Instead, I only get:

   DigiCert Inc (RSA 2048-bit: SHA1)
   DigiCert Inc (RSA 2048-bit: SHA1)
   GitHub, Inc. (RSA 2048-bit: SHA1)

In addition, I'd display the CommonName, rather than the Organization, for the $CERTORG and $CERTISSUER fields, because it is usually more significant.  Note also that the certificate's detail window displays CN:  Consistency may improve understanding, IMHO.

Thanks
Ale

**Comment by gavinhungry** [comment]
@alevesely,

I'm now on Firefox 42, and I can't see the GTE cert anymore. I'm not sure this is something I can fix.

**Comment by gavinhungry** [comment]
Closing, as I haven't heard an update and this is likely out of my hands.
